import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { COLORS } from '../constants/theme';
import { moderateScale } from '../constants/layout';

const CONTACT_EMAIL = 'tncante1008@gmail.com';

const PRIVACY_SECTIONS = [
  {
    heading: 'Overview',
    body: [
      'Ante ("Ante," "the app," "we," "us," or "our") is a personal bankroll and session-tracking application for Blackjack, Poker, Sports Betting, and other wagering activities you engage in independently of the app. This Privacy Policy explains what information Ante interacts with, how it\'s stored, and what control you have over it.',
      `Ante is operated by Tnc, Inc. If you have questions about this policy, contact us at ${CONTACT_EMAIL}.`,
    ],
  },
  {
    heading: 'The short version',
    body: [
      'Ante stores your session and hand data locally on your device. Creating an account is optional; if you sign in, that data also syncs to our server — via Supabase, our database provider — so it\'s available across your devices. If you buy an Ante+ subscription, the purchase is processed by Apple or Google and managed through RevenueCat, our subscription provider. We do not sell or share your information with anyone, and we do not embed any third-party analytics or advertising software in the app.',
    ],
  },
  {
    heading: 'Information Ante stores',
    body: [
      'All of the following is stored in your device\'s local app storage. Items marked "synced" are also stored on our server, but only if and while you are signed in to an account:',
    ],
    bullets: [
      'Session and hand data you enter — bet amounts, outcomes, buy-ins/cash-outs, blind structures, player labels you type in for Poker, and any other figures you log while tracking a session. Synced if you are signed in.',
      'Preferences — your selected currency, privacy mode setting, quick-chip configuration, and responsible-gaming stop-loss threshold. These stay on your device and are not synced.',
      'Account information, if you choose to sign in — your email address and an authentication credential, held by our database provider, Supabase, on our behalf.',
      'Subscription status, if you purchase Ante+ — whether your subscription is active, the plan type (for example annual or lifetime), and its renewal or expiration date. This is reported to us by RevenueCat, which manages subscriptions on our behalf; the underlying payment is processed by Apple or Google, and we never receive your payment card number or billing address. Your subscription is tied to your account if you are signed in, or otherwise to a random identifier generated by RevenueCat.',
      'An anonymous device identifier — a randomly generated string created the first time you open the app, used to identify data you logged before signing in. It is not linked to your name or email, is not used for advertising or cross-app tracking, and is never transmitted off your device.',
    ],
  },
  {
    heading: 'Information Ante does not collect',
    body: [
      'Ante does not request or access your camera, microphone, location, contacts, photo library, or any other device permission. Creating an account is optional — Ante works fully offline without one. If you do sign in, we collect only the email address you provide for authentication; we do not collect your name or phone number. If you purchase an Ante+ subscription, the transaction is handled by Apple\'s App Store or Google Play — we do not receive or store your payment card number, billing address, or other payment details.',
    ],
  },
  {
    heading: 'Third parties',
    body: [
      'Ante relies on two service providers, each acting strictly as our data processor and not using your data for its own purposes:',
    ],
    bullets: [
      'Supabase powers sign-in and cross-device sync. If you sign in, your account and session data is stored with Supabase on our behalf.',
      'RevenueCat manages Ante+ subscriptions. When you purchase or restore a subscription, RevenueCat receives a pseudonymous app-user identifier (linked to your account if you are signed in), your device platform, and the purchase and renewal status reported by the app store. It does not receive your name or payment details. The purchase itself is processed by Apple\'s App Store or Google Play under their own terms and privacy policies.',
    ],
  },
  {
    heading: 'Analytics and advertising',
    body: [
      'Ante does not integrate any third-party analytics SDK, advertising network, or crash-reporting service.',
    ],
  },
  {
    heading: 'Your control over your data',
    body: ['Because most of your data lives on your device, you\'re largely in control of it:'],
    bullets: [
      'Uninstalling the app removes all locally stored Ante data from your device. It does not cancel an Ante+ subscription.',
      `Signing out stops further syncing but does not delete data already stored on our server. Contact us at ${CONTACT_EMAIL} to request deletion of your account and any synced or subscription data.`,
      'Managing your subscription — you can view, cancel, or request a refund for an Ante+ subscription only through your Apple App Store or Google Play account settings; Ante cannot do this for you.',
      'Ante does not currently offer an in-app data export tool. This policy will be updated if that changes.',
    ],
  },
  {
    heading: "Children's privacy",
    body: [
      `Ante is intended for users 18 years of age and older, consistent with our Terms of Service. Ante is not directed at children, and we do not knowingly collect information from anyone under 18. If you believe a child has used the app in a way that concerns you, contact us at ${CONTACT_EMAIL}.`,
    ],
  },
  {
    heading: 'Future changes to how data is handled',
    body: [
      'If Ante adds further data-handling features in the future — such as an in-app export tool or additional integrations — this Privacy Policy will be updated in advance to clearly describe what changes, what\'s collected, and how it\'s protected, with the "Last Updated" date reflecting that change.',
    ],
  },
  {
    heading: 'Changes to this policy',
    body: [
      'We may update this Privacy Policy from time to time. Material changes will be reflected by an updated "Last Updated" date at the top of this page, and, where appropriate, an in-app notice.',
    ],
  },
  {
    heading: 'Contact',
    body: [`Questions about this policy or your data can be sent to ${CONTACT_EMAIL}.`],
  },
];

const TERMS_SECTIONS = [
  {
    heading: '1. Agreement to Terms',
    body: [
      'These Terms of Service ("Terms") govern your access to and use of the Ante mobile application ("Ante," "the app," "we," "us," or "our"), operated by Tnc, Inc. By downloading, installing, or using Ante, you agree to be bound by these Terms. If you do not agree, do not use the app.',
    ],
  },
  {
    heading: '2. Eligibility',
    body: [
      'You must be at least 18 years old to use Ante. By using the app, you represent that you meet this requirement and that your use of the app, and any underlying gambling or wagering activity you choose to track with it, complies with the laws applicable to you in your jurisdiction.',
    ],
  },
  {
    heading: '3. What Ante is — and is not',
    body: [
      'Ante is a personal record-keeping and analytics tool. It lets you log details of gambling or wagering sessions you participate in elsewhere — at a casino, cardroom, sportsbook, or private game — and calculates statistics from what you enter.',
      'Ante does not, at any point, facilitate, process, offer, or accept any real-money wager, bet, or gambling transaction of any kind. Ante has no affiliation, partnership, or integration with any casino, sportsbook, cardroom, lottery, or other gambling operator. Nothing in the app constitutes an offer to gamble, and no money changes hands through Ante.',
    ],
  },
  {
    heading: '4. Not financial, legal, or gambling advice',
    body: [
      'The statistics, insights, and figures Ante generates are calculated from the information you enter and are provided for informational purposes only. They are not financial advice, gambling strategy advice, or a guarantee of future results. You are solely responsible for any decisions you make, gambling or otherwise, based on information Ante provides. Ante does not guarantee the accuracy of any calculation, and you should independently verify any figure that matters to you (e.g., for tax purposes).',
    ],
  },
  {
    heading: '5. Responsible gambling',
    body: [
      'Ante includes optional tools — including a configurable stop-loss alert and access to problem-gambling helpline resources — intended to support more mindful play. These tools are provided as a convenience and are not a substitute for professional help. If you are concerned about your own or someone else\'s gambling, please contact the National Council on Problem Gambling at 1-800-522-4700, or the appropriate resource in your country. Ante is not a treatment provider, counseling service, or medical resource.',
    ],
  },
  {
    heading: '6. Your account and data',
    body: [
      'Ante can be used without an account, in which case your data stays local to your device. You may optionally create an account to sync your data across devices; if you do, your session data is also stored on our server as described in our Privacy Policy. You are responsible for safeguarding access to your own device and account. Ante is not responsible for data loss resulting from device loss, damage, factory reset, app uninstallation, or loss of access to your account.',
    ],
  },
  {
    heading: '7. Ante+ subscriptions and payments',
    body: [
      'Ante is free to download and use. Certain features are grouped into an optional paid subscription called Ante+.',
    ],
    bullets: [
      'Billing. Ante+ is sold as an in-app purchase through the Apple App Store or Google Play. Payment is charged to your App Store or Google Play account when you confirm the purchase. We do not process payments directly and never receive your payment card details.',
      'Auto-renewal. Recurring Ante+ plans renew automatically at the end of each billing period at the then-current price, unless you cancel at least 24 hours before the current period ends. A one-time or lifetime purchase, where offered, does not renew.',
      'Managing and cancelling. You can view, manage, or cancel your subscription, and turn off auto-renewal, only through your Apple App Store or Google Play account settings. Uninstalling the app does not cancel a subscription.',
      'Refunds. All purchases are final except where a refund is required by law. Refund requests are handled by Apple or Google under their policies, not by Tnc, Inc.',
      'Price and plan changes. We may change subscription prices or the set of features included in Ante+. A price change to an existing recurring subscription will be notified in advance as required by the app store and takes effect at your next renewal; you may cancel before then.',
      'Free trials and promotions. Where a free trial is offered, any unused portion is forfeited when you purchase a subscription. Unless stated otherwise, promotional offers are limited to one per user.',
      'What happens when Ante+ ends. If your subscription lapses or is cancelled, Ante+ features become unavailable, but the session and hand data you recorded remains and stays accessible.',
      'Subscription provider. We use RevenueCat to manage and validate subscription entitlements. See our Privacy Policy for what information RevenueCat receives.',
    ],
  },
  {
    heading: '8. Acceptable use',
    body: ['You agree not to:'],
    bullets: [
      'Reverse engineer, decompile, or attempt to extract the source code of the app beyond what applicable law expressly permits;',
      'Use the app for any unlawful purpose, including to facilitate underage or illegal gambling;',
      'Attempt to interfere with, disable, or overload the app;',
      'Copy, resell, sublicense, or redistribute the app or its content without our written permission.',
    ],
  },
  {
    heading: '9. Intellectual property',
    body: [
      'Ante, including its design, branding, source code, and the specific analytics methodology it uses, is owned by Tnc, Inc. Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use the app for your own personal, non-commercial purposes. All rights not expressly granted are reserved.',
    ],
  },
  {
    heading: '10. Disclaimer of warranties',
    body: [
      'Ante is provided "as is" and "as available," without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the app will be uninterrupted, error-free, or that any calculation will be accurate.',
    ],
  },
  {
    heading: '11. Limitation of liability',
    body: [
      'To the fullest extent permitted by law, Tnc, Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, profits, or gambling losses, arising out of or related to your use of the app, even if advised of the possibility of such damages. Our total liability for any claim arising from your use of the app shall not exceed the amount, if any, you paid us to use it in the twelve months preceding the claim.',
    ],
  },
  {
    heading: '12. Indemnification',
    body: [
      'You agree to indemnify and hold harmless Tnc, Inc. from any claim, loss, or demand, including reasonable attorneys\' fees, arising out of your misuse of the app or violation of these Terms or applicable law.',
    ],
  },
  {
    heading: '13. Changes to the app or these Terms',
    body: [
      'We may modify, suspend, or discontinue any part of the app at any time. We may also update these Terms from time to time; material changes will be reflected by an updated "Last Updated" date, and, where appropriate, an in-app notice. Continued use of the app after changes take effect constitutes acceptance of the revised Terms.',
    ],
  },
  {
    heading: '14. Termination',
    body: [
      'We may suspend or terminate your access to the app at any time if we believe you have violated these Terms.',
    ],
  },
  {
    heading: '15. Governing law',
    body: [
      'These Terms are governed by the laws of the Province of British Columbia and the federal laws of Canada applicable therein, without regard to conflict-of-laws principles. You and Tnc, Inc. submit to the exclusive jurisdiction of the courts located in British Columbia, Canada for any dispute arising from these Terms or your use of the app.',
    ],
  },
  {
    heading: '16. Severability',
    body: [
      'If any provision of these Terms is found unenforceable, the remaining provisions will remain in full force and effect.',
    ],
  },
  {
    heading: '17. Contact',
    body: [`Questions about these Terms can be sent to ${CONTACT_EMAIL}.`],
  },
];

const DOC_CONFIG = {
  privacy: {
    title: 'Privacy Policy',
    lastUpdated: 'September 1, 2026',
    sections: PRIVACY_SECTIONS,
  },
  terms: {
    title: 'Terms of Service',
    lastUpdated: 'September 1, 2026',
    sections: TERMS_SECTIONS,
  },
};

export default function LegalScreen({ route, navigation }) {
  const doc = DOC_CONFIG[route?.params?.doc] || DOC_CONFIG.privacy;
  const insets = useSafeAreaInsets();

  return (
    <SafeAreaView style={styles.safeArea} edges={['top', 'left', 'right']}>
      <View style={styles.topNav}>
        <Ionicons
          name="chevron-back"
          size={22}
          color={COLORS.textPrimary}
          onPress={() => navigation.goBack()}
          style={styles.backIcon}
        />
        <Text style={styles.navTitle}>{doc.title}</Text>
        <View style={{ width: 22 }} />
      </View>

      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingBottom: insets.bottom + moderateScale(40) }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.lastUpdated}>Last Updated: {doc.lastUpdated}</Text>

        {doc.sections.map((section, idx) => (
          <View key={idx} style={styles.section}>
            <Text style={styles.sectionHeading}>{section.heading}</Text>
            {section.body.map((p, pIdx) => (
              <Text key={pIdx} style={styles.paragraph}>
                {p}
              </Text>
            ))}
            {section.bullets && (
              <View style={styles.bulletList}>
                {section.bullets.map((b, bIdx) => (
                  <View key={bIdx} style={styles.bulletRow}>
                    <Text style={styles.bulletDot}>•</Text>
                    <Text style={styles.bulletText}>{b}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  topNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorder,
  },
  backIcon: { padding: 4 },
  navTitle: { fontSize: 16, fontWeight: '700', color: COLORS.textPrimary },
  scroll: { padding: 16 },
  lastUpdated: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: '600',
    marginBottom: 18,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 20,
    marginBottom: 8,
  },
  bulletList: {
    marginTop: 2,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingRight: 4,
  },
  bulletDot: {
    fontSize: 13,
    color: COLORS.primary,
    marginRight: 8,
    lineHeight: 20,
  },
  bulletText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
});
