// Styles for ProfileScreen, kept alongside it rather than inside it — the
// screen renders seven unrelated sections and its stylesheet was long enough
// to bury the ones that matter.
import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../constants/theme';
import { moderateScale, fluidFont, SPACING, RADIUS, TOUCH_TARGET } from '../constants/layout';

export const styles = StyleSheet.create({
  contentContainer: {
    paddingHorizontal: SPACING.pageHorizontal,
    paddingTop: SPACING.sm,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.xs,
    marginBottom: SPACING.md,
  },
  title: {
    fontSize: fluidFont(24),
    fontWeight: '700',
    color: COLORS.textPrimary,
    letterSpacing: 1,
  },
  // Stake-Style Profile Card
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.lg,
    padding: SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    marginBottom: SPACING.lg,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: SPACING.sm + 2,
  },
  avatarCircle: {
    width: moderateScale(54),
    height: moderateScale(54),
    borderRadius: moderateScale(27),
    backgroundColor: COLORS.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  onlineBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: moderateScale(14),
    height: moderateScale(14),
    borderRadius: moderateScale(7),
    backgroundColor: COLORS.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onlineDot: {
    width: moderateScale(9),
    height: moderateScale(9),
    borderRadius: moderateScale(4.5),
    backgroundColor: COLORS.success,
  },
  profileMeta: {
    flex: 1,
  },
  userNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userName: {
    fontSize: fluidFont(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
    letterSpacing: 0.3,
  },
  userHandle: {
    fontSize: fluidFont(12),
    color: COLORS.textSecondary,
    marginTop: 1,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  signInButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    paddingVertical: moderateScale(13),
    marginBottom: SPACING.lg,
  },
  signInButtonText: {
    color: COLORS.textDark,
    fontWeight: '700',
    fontSize: fluidFont(14),
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingVertical: moderateScale(13),
    marginBottom: SPACING.lg,
  },
  signOutButtonText: {
    color: COLORS.danger,
    fontWeight: '700',
    fontSize: fluidFont(14),
  },

  // 2x2 Vault Grid
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xs,
    marginLeft: 2,
  },
  sectionTitle: {
    fontSize: fluidFont(13),
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 1,
    marginBottom: SPACING.xs,
    marginLeft: 2,
  },
  privacyToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  privacyToggleText: {
    fontSize: fluidFont(12),
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  grid2x2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
    marginBottom: SPACING.lg,
  },
  gridCard: {
    width: '48.5%',
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.md,
    padding: moderateScale(14),
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  gridCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  gridCardLabel: {
    fontSize: fluidFont(10),
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.8,
  },
  gridCardValue: {
    fontSize: fluidFont(20),
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  gridCardFoot: {
    fontSize: fluidFont(11),
    color: COLORS.textMuted,
    marginTop: 4,
  },

  // Menu Settings Cards
  menuCard: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    marginBottom: SPACING.lg,
  },
  proMenuCard: {
    borderColor: COLORS.primaryGlow,
    paddingBottom: SPACING.sm,
  },
  proIconCircle: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.primaryGlow,
  },
  proActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    paddingVertical: moderateScale(12),
    marginBottom: SPACING.sm,
  },
  proActionBtnText: {
    color: COLORS.textDark,
    fontWeight: '700',
    fontSize: fluidFont(14),
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: moderateScale(14),
    minHeight: TOUCH_TARGET.minSize,
  },
  menuIconCircle: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  menuTextGroup: {
    flex: 1,
    marginRight: SPACING.xs,
  },
  menuTitle: {
    fontSize: fluidFont(14),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  menuSubtitle: {
    fontSize: fluidFont(11),
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  menuDivider: {
    height: 1,
    backgroundColor: COLORS.cardBorder,
    marginLeft: moderateScale(48),
  },
  chevronContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  currencyList: { maxHeight: moderateScale(400) },
  currencyListContent: { paddingBottom: 2 },
  copyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primaryMuted,
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(4),
    borderRadius: RADIUS.xs,
    gap: 4,
  },
  copyBadgeText: {
    fontSize: fluidFont(11),
    fontWeight: '700',
    color: COLORS.primary,
  },

  // Footer
  footerInfo: {
    alignItems: 'center',
    marginTop: SPACING.xs,
    marginBottom: SPACING.md,
  },
  versionText: {
    fontSize: fluidFont(12),
    color: COLORS.textMuted,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  copyrightText: {
    fontSize: fluidFont(11),
    color: COLORS.textMuted,
    marginTop: 2,
  },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.pageHorizontal,
  },
  modalSheet: {
    width: '100%',
    backgroundColor: COLORS.backgroundSecondary,
    borderRadius: RADIUS.lg,
    padding: SPACING.cardPadding,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  modalTitle: {
    fontSize: fluidFont(18),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  currencyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: moderateScale(12),
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.card,
    marginBottom: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  currencyOptionSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryMuted,
  },
  currencySymbolBox: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: RADIUS.xs,
    backgroundColor: COLORS.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
  },
  currencySymbolLarge: {
    fontSize: fluidFont(16),
    fontWeight: '700',
    color: COLORS.primary,
  },
  currencyItemName: {
    fontSize: fluidFont(14),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  currencyItemId: {
    fontSize: fluidFont(11),
    color: COLORS.textMuted,
    marginTop: 1,
  },
  limitBlock: {
    marginBottom: SPACING.md,
  },
  limitTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  limitLabel: {
    fontSize: fluidFont(14),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  limitSub: {
    fontSize: fluidFont(12),
    color: COLORS.textSecondary,
    marginTop: 2,
    marginBottom: SPACING.xs,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingHorizontal: moderateScale(12),
    height: moderateScale(44),
  },
  inputPrefix: {
    fontSize: fluidFont(16),
    fontWeight: '700',
    color: COLORS.primary,
    marginRight: 6,
  },
  inputSuffix: {
    fontSize: fluidFont(12),
    fontWeight: '600',
    color: COLORS.textMuted,
    marginLeft: 6,
  },
  textInput: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: fluidFont(16),
    fontWeight: '700',
    padding: 0,
  },
  saveModalBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    paddingVertical: moderateScale(13),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.sm,
  },
  saveModalBtnText: {
    color: COLORS.textDark,
    fontSize: fluidFont(14),
    fontWeight: '700',
  },
  saveModalBtnBusy: {
    opacity: 0.7,
  },
  secondaryModalBtn: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorderHighlight,
    paddingVertical: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.xs,
  },
  secondaryModalBtnText: {
    color: COLORS.textPrimary,
    fontSize: fluidFont(14),
    fontWeight: '700',
  },
  accountError: {
    fontSize: fluidFont(12),
    color: COLORS.danger,
    marginTop: SPACING.xs,
  },
  deleteNote: {
    fontSize: fluidFont(12),
    color: COLORS.textMuted,
    lineHeight: fluidFont(17),
    marginBottom: SPACING.sm,
  },
  deleteConfirmPrompt: {
    fontSize: fluidFont(12),
    color: COLORS.textSecondary,
    lineHeight: fluidFont(17),
    marginBottom: SPACING.xs,
  },
  // Wraps onto its own line(s) when the address is long, instead of being
  // clipped the way placeholder text would be.
  deleteConfirmEmail: {
    color: COLORS.textPrimary,
    fontWeight: '700',
  },
  deleteModalBtn: {
    backgroundColor: COLORS.dangerMuted,
    borderWidth: 1,
    borderColor: COLORS.dangerBorder,
    borderRadius: RADIUS.sm,
    paddingVertical: moderateScale(13),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.sm,
  },
  deleteModalBtnText: {
    color: COLORS.danger,
    fontSize: fluidFont(14),
    fontWeight: '700',
  },
  deleteModalBtnDisabled: {
    opacity: 0.45,
  },
  noticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: -SPACING.md,
    marginBottom: SPACING.lg,
    marginLeft: 2,
  },
  noticeText: {
    fontSize: fluidFont(12),
    color: COLORS.success,
    fontWeight: '600',
  },
  helpText: {
    fontSize: fluidFont(13),
    color: COLORS.textSecondary,
    lineHeight: fluidFont(18),
    marginBottom: SPACING.md,
  },
  helpBox: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.sm,
    padding: moderateScale(14),
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    marginBottom: SPACING.md,
  },
  helpBoxTitle: {
    fontSize: fluidFont(14),
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  helpBoxSub: {
    fontSize: fluidFont(12),
    color: COLORS.textMuted,
    marginTop: 2,
  },
  helpPhone: {
    fontSize: fluidFont(16),
    fontWeight: '700',
    color: COLORS.accentCyan,
    marginTop: 6,
    letterSpacing: 0.5,
  },

  // Quick Chip Preset modal
  chipGameRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
    marginBottom: SPACING.sm,
  },
  chipGameBtn: {
    flex: 1,
    paddingVertical: moderateScale(9),
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipGameBtnActive: {
    backgroundColor: COLORS.primaryMuted,
    borderColor: COLORS.primary,
  },
  chipGameBtnText: {
    fontSize: fluidFont(12),
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  chipGameBtnTextActive: {
    color: COLORS.primary,
  },
  chipPresetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
    marginTop: SPACING.xs,
    marginBottom: SPACING.sm,
  },
  chipPresetBox: {
    width: '31%',
  },
  chipPresetLabel: {
    fontSize: fluidFont(10),
    fontWeight: '700',
    color: COLORS.textMuted,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  chipPresetInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingHorizontal: moderateScale(8),
    height: moderateScale(42),
  },
  chipPresetPrefix: {
    fontSize: fluidFont(13),
    fontWeight: '700',
    color: COLORS.primary,
    marginRight: 3,
  },
  chipPresetInput: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: fluidFont(14),
    fontWeight: '700',
    padding: 0,
  },
});
